[package]
name = "smsr"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = { version = "0.3.*" }
tokio = { version = "1.40.0", features = ["full"] }
log = "0.4.*"
env_logger = "0.11.5"
reqwest = { version = "0.12.8" }
